[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ISE-dataset"
authors = [{name = "ZhipengXue", email = "zhipengxue@zju.edu.cn"},
{name = "ZhipengGao", email = "zhipeng.gao@zju.edu.cn"}]
dynamic = ["version", "description"]
